### ISSUE TITLE
Reverse flamegraphs

### ISSUE THREAD

**Issue by ethercrow** [marcin-rzeznicki/stackcollapse-ghc#1]
Is it possible to add a reverse mode, where at the bottom you have the "leaf" functions and their callers are on top of them and callers of the callers are even higher and so on?

This mode is useful because it brings to attention functions that are called from many different places, but in every individual place it's relatively minor. E.g. you have 100 equally heavy operations in your program and each one of those calls a `writeLog` function. In the standard flamegraph you'd have to hover a lot and do some pattern matching in your head to spot it. In a reverse flamegraph it would be an obvious chunk at the very bottom, with 100 callers on top of it.

**Comment by marcin-rzeznicki** [comment]
Hey @ethercrow - thanks so much for opening the first issue! :partying_face: 

Is this not covered by the [reverse](https://github.com/brendangregg/FlameGraph#options) option in the flamegraph script?

**Comment by ethercrow** [comment]
Hi Marcin! Yes, that is exactly it. I just saw this feature implemented in another system that was doing both stack processing and flamegraphing and assumed that reversing must be done in the stack processing part. I'm happy to be wrong here!

What do you think about adding an example of a reverse flamegraph to the readme?

**Comment by marcin-rzeznicki** [comment]
Dimitrij :wave:  excellent idea. I'm going to add it soon
